#docker-compose -f backend.yml up -d
version: '3.1'

services:
    db:
        image: mysql
        container_name: mysql
        hostname: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: learninglanguage
        ports:
            - 3306:3306
        networks:
            - escoladeti
    backend:
        image: escoladeti-backend
        container_name: escoladeti-backend
        hostname: escoladeti-backend
        ports:
            - 3000:3000
        networks:
            - escoladeti

    frontend:
        image: escoladeti-frontend
        container_name: escoladeti-frontend
        hostname: escoladeti-frontend
        ports:
            - 80:80
        networks:
            - escoladeti

networks:
    escoladeti:
